id: P8A7AB66B
initial_creation_type: ocr
source_metadata:
  volumes:
    75501dde288c4bcd8dea63632b1c8f5c:
      base_file: v064.txt
      image_group_id: I1PD95909
      title: བསྒོམ་རིམ་བར་མ།
      total_pages: 1902
      volume_number: 64
