id: D68019E4D
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-02-24T10:30:30+00:00'
last_modified: '2022-05-27T15:06:05.121230+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    c92b:
      image_group_id: I1PD95909
      title: བསྒོམ་རིམ་བར་མ།
      total_pages: 1902
      order: 64
      base_file: c92b.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
